//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CosRomCieSabana
    {
        public long CosRomCieSabanaId { get; set; }
        public Nullable<System.DateTime> Periodo { get; set; }
        public string OperadorId { get; set; }
        public Nullable<decimal> ProvTarifa { get; set; }
        public Nullable<decimal> TotalProvTarifa { get; set; }
        public Nullable<decimal> ProvRealReg { get; set; }
        public Nullable<decimal> NuevaProvAcumMesAnte { get; set; }
        public Nullable<decimal> NuevaProvAcum { get; set; }
    }
}
