//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FluctuacionIngresoROM
    {
        public int id { get; set; }
        public string no_Provision { get; set; }
        public string cuenta_Contable { get; set; }
        public string pmln { get; set; }
        public string nombre { get; set; }
        public string deudor { get; set; }
        public string sociedad_GL { get; set; }
        public string periodo { get; set; }
        public string tipo { get; set; }
        public string tipo_Registro { get; set; }
        public string documento { get; set; }
        public string no_DocumentoSap { get; set; }
        public string moneda { get; set; }
        public Nullable<decimal> tC_Provision { get; set; }
        public Nullable<decimal> tC_Cierre { get; set; }
        public Nullable<decimal> tC_Facturado { get; set; }
        public Nullable<decimal> importe_Provision { get; set; }
        public Nullable<decimal> importe_ProvisionMXN { get; set; }
        public Nullable<decimal> importe_Revaluado { get; set; }
        public Nullable<decimal> importe_Facturado { get; set; }
        public Nullable<decimal> importe_Facturado_Provision { get; set; }
        public Nullable<decimal> facturado_MXN { get; set; }
        public Nullable<decimal> variacion_MXN { get; set; }
        public Nullable<decimal> efecto_Operativo { get; set; }
        public Nullable<decimal> fluctuacion_Cambiaria { get; set; }
        public string estatus { get; set; }
        public string cuenta_Fluctuacion { get; set; }
        public System.DateTime fecha_Carga { get; set; }
    }
}
