//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngRomCieProvTarifa
    {
        public long IngRomCieProvTarifaId { get; set; }
        public long OperadorId { get; set; }
        public System.DateTime Periodo { get; set; }
        public Nullable<decimal> ProvTarifa { get; set; }
        public Nullable<decimal> AjNcRealVsDevengoMesAnte { get; set; }
        public Nullable<decimal> ProvDevengoTarifa { get; set; }
        public Nullable<decimal> ProvisionNcTarifaCancelada { get; set; }
        public Nullable<decimal> ProvisionNcTarifa { get; set; }
        public Nullable<decimal> TotalProvisionNcTarifa { get; set; }
        public Nullable<decimal> ProvisionIngresoTarifa { get; set; }
        public Nullable<decimal> CancelacionProvisionIngresoTarifa { get; set; }
        public Nullable<decimal> TotalProvIngresoTarifa { get; set; }
        public Nullable<decimal> ComplementoTarifaMesesAnteriores { get; set; }
        public Nullable<decimal> TotalProvTarifa { get; set; }
    }
}
