//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngRomCieDevengoAcumuladoTrafico
    {
        public long IngRomCieDevengoAcumuladoId { get; set; }
        public long OperadorId { get; set; }
        public System.DateTime Periodo { get; set; }
        public Nullable<decimal> DevengoTrafico { get; set; }
        public Nullable<decimal> DevengoPendienteFacturar { get; set; }
        public Nullable<decimal> DevengoAcumulado { get; set; }
    }
}
