//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngRomCieSabana
    {
        public long IngRomCieSabanaId { get; set; }
        public int OperadorId { get; set; }
        public System.DateTime Periodo { get; set; }
        public Nullable<decimal> Devengo { get; set; }
        public Nullable<decimal> DevengoAcum { get; set; }
        public Nullable<decimal> NcAcumMesActual { get; set; }
        public Nullable<decimal> TotalNcEmitida { get; set; }
        public Nullable<decimal> Acum { get; set; }
        public Nullable<decimal> TotalSabana { get; set; }
    }
}
