//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class permisos
    {
        public int Id { get; set; }
        public int IDMenu { get; set; }
        public int ID_Perfil { get; set; }
        public int CanRead { get; set; }
        public int CanNew { get; set; }
        public int CanEdit { get; set; }
        public int CanDelete { get; set; }
        public int WriteLog { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string UserModify { get; set; }
        public bool Activo { get; set; }
    
        public virtual MenuIC MenuIC { get; set; }
        public virtual Perfil Perfil { get; set; }
    }
}
