//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PXQIngresosROMRecalculo
    {
        public long PXQIngresosROMRecalculo1 { get; set; }
        public int PXQIngresosROMB { get; set; }
        public Nullable<decimal> IOT_TAR_MOC { get; set; }
        public Nullable<decimal> IOT_TAR_MTC { get; set; }
        public Nullable<decimal> IOT_TAR_SMS_MO { get; set; }
        public Nullable<decimal> IOT_TAR_GPRS { get; set; }
        public Nullable<decimal> USD_MOC_IOTFacturado { get; set; }
        public Nullable<decimal> USD_MTC_IOTFacturado { get; set; }
        public Nullable<decimal> USD_SMS_MO_IOTFacturado { get; set; }
        public Nullable<decimal> USD_GPRS_IOTFacturado { get; set; }
        public Nullable<decimal> USD_MOC_IOT_REAL { get; set; }
        public Nullable<decimal> USD_MTC_IOT_REAL { get; set; }
        public Nullable<decimal> USD_MOC_IOT_DESC { get; set; }
        public Nullable<decimal> USD_MTC_IOT_DESC { get; set; }
        public Nullable<decimal> USD_SMS_MO_IOT_DESC { get; set; }
        public Nullable<decimal> USD_GPRS_IOT_DESC { get; set; }
    }
}
