//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uvw_CargaDocumentoRoaming
    {
        public int Id { get; set; }
        public string IdDocumento { get; set; }
        public Nullable<System.DateTime> PeriodoCarga { get; set; }
        public Nullable<System.DateTime> FechaCarga { get; set; }
        public string TipoCarga { get; set; }
        public string OrdenCarga { get; set; }
        public string EstatusCarga { get; set; }
    }
}
