//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uvw_FluctuacionTarifasCosto
    {
        public string NumeroProvision { get; set; }
        public string CuentaContable { get; set; }
        public string Operador { get; set; }
        public string Nombre { get; set; }
        public string Acreedor { get; set; }
        public string SociedadGL { get; set; }
        public Nullable<System.DateTime> Periodo { get; set; }
        public string Tipo { get; set; }
        public string TipoRegistro { get; set; }
        public string Documento { get; set; }
        public string NumeroDocumentoSap { get; set; }
        public string Moneda { get; set; }
        public Nullable<decimal> TipoCambioProvision { get; set; }
        public Nullable<decimal> TipoCambioCierre { get; set; }
        public Nullable<decimal> TipoCambioFacturado { get; set; }
        public Nullable<decimal> ImporteProvision { get; set; }
        public Nullable<decimal> ImporteProvisionMXN { get; set; }
        public Nullable<decimal> ImporteRevaluado { get; set; }
        public Nullable<decimal> ImporteFacturado { get; set; }
        public Nullable<decimal> ImporteFacturadoProvision { get; set; }
        public Nullable<decimal> FacturadoMXN { get; set; }
        public Nullable<decimal> VariacionMXN { get; set; }
        public Nullable<decimal> EfectoOperativo { get; set; }
        public Nullable<decimal> FluctuacionCambiaria { get; set; }
        public string Estatus { get; set; }
        public Nullable<int> CuentaFluctuacion { get; set; }
        public Nullable<int> IdAcreedor { get; set; }
        public Nullable<int> IdMoneda { get; set; }
        public Nullable<int> IdOperador { get; set; }
        public Nullable<System.DateTime> FechaCarga { get; set; }
        public Nullable<int> PeriodoCargaMes { get; set; }
        public Nullable<int> PeriodoCargaAnio { get; set; }
    }
}
